name: Empty Spam Folder v2

on:
  schedule:
    - cron: "0 * * * *" # force trigger registration
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run script
        env:
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python ziggo_cleanup.py

      - name: Upload log file
        uses: actions/upload-artifact@v4
        with:
          name: cleanup-log
          path: cleanup_log.txt
